# Site settings
title: "On Software Engineering, Mathematics and Philosophy"
author: "Lulzx"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a computer science student from South Asia. Here you can <a href='https:t.me/lulzx'>Talk to me</a>."
colophon: "Â© MMXIX by Lulzx.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/''>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/''>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a> and <a href='http://getbootstrap.com'>Bootstrap</a>."

baseurl: ""
url: "https://lulzx.github.io"

twitter_username: lulzx
github_username: lulzx
linkedin_username: lulzx
facebook_username: lulzx
instagram_username: lulzx
500px_username: lulzx

google-analytics: xxx

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

plugins:
- jekyll-sitemap
